# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkboc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 300, 101, 91))
        self.label.setText("")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(80, 70, 191, 171))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 111, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbsinema = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbsinema.setObjectName("cbsinema")
        self.verticalLayout.addWidget(self.cbsinema)
        self.cbspor = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbspor.setObjectName("cbspor")
        self.verticalLayout.addWidget(self.cbspor)
        self.cbkitapokuma = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbkitapokuma.setObjectName("cbkitapokuma")
        self.verticalLayout.addWidget(self.cbkitapokuma)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(290, 70, 191, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 40, 111, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbsinema_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbsinema_2.setObjectName("cbsinema_2")
        self.verticalLayout_2.addWidget(self.cbsinema_2)
        self.cbspor_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbspor_2.setObjectName("cbspor_2")
        self.verticalLayout_2.addWidget(self.cbspor_2)
        self.cbkitapokuma_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.cbkitapokuma_2.setObjectName("cbkitapokuma_2")
        self.verticalLayout_2.addWidget(self.cbkitapokuma_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 260, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 290, 101, 91))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbsinema.setText(_translate("MainWindow", "Sinema"))
        self.cbspor.setText(_translate("MainWindow", "Kitap Okumak"))
        self.cbkitapokuma.setText(_translate("MainWindow", "Spor"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbsinema_2.setText(_translate("MainWindow", "Sinema"))
        self.cbspor_2.setText(_translate("MainWindow", "Kitap Okumak"))
        self.cbkitapokuma_2.setText(_translate("MainWindow", "Spor"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
