# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_listview.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 60, 171, 371))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Add = QtWidgets.QPushButton(self.layoutWidget)
        self.Add.setObjectName("Add")
        self.verticalLayout.addWidget(self.Add)
        self.Edit = QtWidgets.QPushButton(self.layoutWidget)
        self.Edit.setObjectName("Edit")
        self.verticalLayout.addWidget(self.Edit)
        self.Remove = QtWidgets.QPushButton(self.layoutWidget)
        self.Remove.setObjectName("Remove")
        self.verticalLayout.addWidget(self.Remove)
        self.Up = QtWidgets.QPushButton(self.layoutWidget)
        self.Up.setObjectName("Up")
        self.verticalLayout.addWidget(self.Up)
        self.Down = QtWidgets.QPushButton(self.layoutWidget)
        self.Down.setObjectName("Down")
        self.verticalLayout.addWidget(self.Down)
        self.sort = QtWidgets.QPushButton(self.layoutWidget)
        self.sort.setObjectName("sort")
        self.verticalLayout.addWidget(self.sort)
        spacerItem = QtWidgets.QSpacerItem(0, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exit = QtWidgets.QPushButton(self.layoutWidget)
        self.exit.setObjectName("exit")
        self.verticalLayout.addWidget(self.exit)
        self.listitem = QtWidgets.QListWidget(self.centralwidget)
        self.listitem.setGeometry(QtCore.QRect(40, 60, 361, 371))
        self.listitem.setObjectName("listitem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Edit.setText(_translate("MainWindow", "Edit"))
        self.Remove.setText(_translate("MainWindow", "Remove"))
        self.Up.setText(_translate("MainWindow", "Up"))
        self.Down.setText(_translate("MainWindow", "Down"))
        self.sort.setText(_translate("MainWindow", "Sort"))
        self.exit.setText(_translate("MainWindow", "Exit"))
