# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(497, 428)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.sayi1 = QtWidgets.QLineEdit(self.centralwidget)
        self.sayi1.setGeometry(QtCore.QRect(60, 20, 113, 20))
        self.sayi1.setObjectName("sayi1")
        self.sayi2 = QtWidgets.QLineEdit(self.centralwidget)
        self.sayi2.setGeometry(QtCore.QRect(60, 40, 113, 20))
        self.sayi2.setObjectName("sayi2")
        self.toplama = QtWidgets.QPushButton(self.centralwidget)
        self.toplama.setGeometry(QtCore.QRect(80, 70, 75, 23))
        self.toplama.setObjectName("toplama")
        self.cikarma = QtWidgets.QPushButton(self.centralwidget)
        self.cikarma.setGeometry(QtCore.QRect(80, 100, 75, 23))
        self.cikarma.setObjectName("cikarma")
        self.carpma = QtWidgets.QPushButton(self.centralwidget)
        self.carpma.setGeometry(QtCore.QRect(80, 130, 75, 23))
        self.carpma.setObjectName("carpma")
        self.bolme = QtWidgets.QPushButton(self.centralwidget)
        self.bolme.setGeometry(QtCore.QRect(80, 160, 75, 23))
        self.bolme.setObjectName("bolme")
        self.sonuc = QtWidgets.QLabel(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(190, 30, 47, 13))
        self.sonuc.setObjectName("sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sayı 1:"))
        self.label_2.setText(_translate("MainWindow", "Sayı 2:"))
        self.toplama.setText(_translate("MainWindow", "Toplama"))
        self.cikarma.setText(_translate("MainWindow", "Çıkarma"))
        self.carpma.setText(_translate("MainWindow", "Çarpma"))
        self.bolme.setText(_translate("MainWindow", "Bölme"))
        self.sonuc.setText(_translate("MainWindow", "Sonuç: "))
